name: Build and test
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [cp38-cp38, cp39-cp39, cp310-cp310, cp311-cp311]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Build using manylinux
        shell: bash
        run: scripts/build.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Install deps
        shell: bash
        run: pip3 install auditwheel

      - name: Fix wheel
        shell: bash
        run:
          auditwheel repair --plat manylinux2014_x86_64 dist/*

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version }}
          path: wheelhouse/*.whl

  macos:
    strategy:
      matrix:
        python-version: [ ["3.8", "38"], ["3.9", "39"], ["3.10", "310"], ["3.11", "311"] ]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        name: Setting up Python env
        with:
          python-version: ${{ matrix.python-version[0] }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_BUILD: cp${{ matrix.python-version[1] }}-macosx_universal2
          CIBW_ARCHS_MACOS: universal2
          CIBW_TEST_SKIP: '*universal2:arm64'

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version[0] }}-${{ matrix.os }}
          path: wheelhouse/*.whl

  win:
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        name: Setting up Python env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheel
        shell: bash
        run: |
          pip3 install wheel
          python3 setup.py bdist_wheel
          mv dist wheelhouse
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version }}-${{ matrix.os }}
          path: wheelhouse/*.whl

  test:
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [linux, macos, win]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Setting up Python env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: wheelhouse
      - name: Reorganize wheels
        working-directory: wheelhouse
        run: |
          mv */*.whl .
          find . -empty -type d -delete
          ls -R .

      - name: Install wheel
        shell: bash
        run: |
          pip3 install pytest
          pip3 install uinspect --find-links wheelhouse --no-index

      - name: Test
        shell: bash
        run: pytest tests/ -v

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: wheelhouse
      - name: Reorganize wheels
        working-directory: wheelhouse
        run: |
          mv */*.whl .
          find . -empty -type d -delete
          ls -R .
      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.5
        if: startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse
          skip_existing: true
