name: Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310, cp311-cp311 ]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          
      - name: Start manylinux
        shell: bash
        run: scripts/build.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Install deps
        shell: bash
        run: |
          sudo apt update && sudo apt install patchelf
          pip3 install auditwheel pytest

      - name: Fix wheel
        shell: bash
        run:
          auditwheel repair --plat manylinux2014_x86_64 dist/*

      - name: Install wheel
        shell: bash
        run: pip3 install uinspect --find-links wheelhouse --no-index

      - name: Test
        shell: bash
        run: pytest tests/ -v
