name: Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310 ] # cp311-cp311

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Build using manylinux
        shell: bash
        run: scripts/build.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Install deps
        shell: bash
        run: pip3 install auditwheel

      - name: Fix wheel
        shell: bash
        run:
          auditwheel repair --plat manylinux2014_x86_64 dist/*

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version }}
          path: wheelhouse/*.whl


  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: wheelhouse
      - name: Reorganize wheels
        working-directory: wheelhouse
        run: mv */*.whl .

      - name: Install wheel
        shell: bash
        run: |
          pip3 install pytest
          pip3 install uinspect --find-links wheelhouse --no-index

      - name: Test
        shell: bash
        run: pytest tests/ -v
